---
apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
spec:
  containers:
    - name: container-1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      resources:
        limits:
          memory: '1Gi'
          cpu: '800m'
        requests:
          memory: '700Mi'
          cpu: '400m'
  
    - name: container-2
      image: redis
      command:
        - redis-server
      volumeMounts:
        - mountPath: /tmp/
          name: workdir
      resources: {}

    - name: container-3
      image: busybox
      command: ["sh", "-c", "echo 'giropops strigus girus' > /tmp/toskao"]
      volumeMounts:
        - mountPath: /tmp/
          name: workdir
      resources: {}
          
  # These containers are run during pod initialization
  dnsPolicy: Default
  volumes:
    - name: workdir
      emptyDir: {}
